version: "3.9"

services:

  rpc:
    image: node:12
    command: bash -c "npm install && npx truffle develop"
    working_dir: /app
    volumes:
      - ./rpc:/app
    ports:
      - ${PORT_RPC}:9545

  api:
    image: node:16
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./api:/app
      - ./storage:/storage
    ports:
      - ${PORT_API}:4000
    environment:
      API_PORT: ${PORT_API}
      RPC_URI: http://rpc:9545
      MONGO_URI: mongodb://mongo:27017
      PINIATA_JWT: ${PINIATA_JWT}

  web:
    image: node:16
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - ${PORT_WEB}:3000
    environment:
      WDS_SOCKET_PORT: ${PORT_WEB}

  mongo:
    image: mongo:4.4
    volumes:
      - ./storage/dbs/mongo:/data/db
    ports:
      - ${PORT_MONGO}:27017
